Update public.py
NelsonDane/public-invest-api pull request #6
Opened 2024-04-30 22:54 UTC by Cfomodz

adding missing limit_price param (order_type specified LIMIT was acceptable but no mechanism was in place to attach the desired limit price leading to preflight failure of order)

+ Added the .text of the response if status code is not 200 for debugging/error handling

2024-04-30 22:58 UTC, Cfomodz commented
I don't _mind_ restructuring the function to make DeepSource happy.. but I was trying to make as few changes as possible to the flow considering it's my first contribution to the project 😅

2024-04-30 23:28 UTC, NelsonDane commented
> I don't _mind_ restructuring the function to make DeepSource happy.. but I was trying to make as few changes as possible to the flow considering it's my first contribution to the project 😅

No worries, the specific issue it was fussing about I usually disabled in other repos too, so it's all good now :)

2024-04-30 23:29 UTC, NelsonDane requested changes
Thanks so much for the contribution! Functionality looks fine, just some tiny style things.

2024-04-30 23:29 UTC, NelsonDane commented on README.md
> +    limit_price=None # pass if using 'LIMIT' order_type
I'd make a note that this can be a float/decimal value. Like "pass float if using..."

2024-04-30 23:29 UTC, NelsonDane commented on public_invest_api/public.py
> +            raise Exception(f"Build order failed - {build_response.text}")
Use a `:` instead of the dash here to match some of the other Exceptions

2024-05-01 23:37 UTC, Cfomodz commented
o7

2024-05-01 23:40 UTC, NelsonDane approved these changes
LGTM

2024-05-01 23:41 UTC, merged